### ISSUE TITLE
Star reports 

### ISSUE THREAD

**Issue by ekarige** [CodeForAfrica/CitizenReporter#31]
1. Logging in to star reports was a tiring process took me almost (cumulative ) 30 minutes (getting bored and frustrated and choosing to do something else )  to figure out I can not use my email to sign in and instead use my username. In the log in page the text box reads email and username. 
2. Creating a report this also took some time ( my impatience was at play ) not necessary an issue but an observation. The app crushed halfway through my entry . Defiantly a bad sign. 
3. We have starreports.co.ke url - can we redirect http://starreports.codeforafrica.net/ to starreports.co.ke.
4. In the dashboard - i was able to log in using my app username and password. Can we have a layer access ?  

Hope I have helped .

**Comment by nickhargreaves** [comment]
Thanks for testing the app and posting the issues. I'm closing this issue but adding the different issues as separate items.
