### ISSUE TITLE
Crashed on Storyboard

### ISSUE THREAD

**Issue by nickhargreaves** [CodeForAfrica/CitizenReporter#34]

**Comment by nickhargreaves** [comment]
hey @ekarige, could you let me know what exactly you were doing. Also the phone model and OS version would be helpful. You can find these details on the settings > about device section of your phone.

**Comment by ekarige** [comment]
@nickhargreaves. 
Model - Techno-j7
android version - 4.4.2

I was working on uploading an picture story . I was answering or rather filling in the questions

**Comment by nickhargreaves** [comment]
hey @ekarige I haven't been able to replicate this crash on a test device with similar OS. Could you try to replicate it on your phone. And then if it crashes again choose the 'report' option on the dialog that comes up. 
We should do the same every time it crashes, so I can better understand the cause.
